--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/jasonw4331/Commando
projects:
  Commando:
    model: virion
    type: library
    libs:
      - src: Muqsit/SimplePacketHandler/SimplePacketHandler
        version: ^0.1.3
...
